# Generated by Django 5.0 on 2024-02-11 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 2, 11, 0, 0, 0, 551256, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='Tickets',
        ),
    ]
